# Reference: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/workflows/matrix.yml
name: Cataclysm Compiler

on:
  workflow_dispatch:
    inputs:
      target-repo:
        description: 'Target repository for compilation'
        required: true
        default: 'CleverRaven'
        type: choice
        options:
          - 'sonphantrung'
          - 'casswedson'
          - 'CleverRaven'
          - 'NOPE'

concurrency:
  group: cataclysm-build
  cancel-in-progress: true

jobs:
  linux-compiler:
    continue-on-error: true
    runs-on: macos-13
    steps:

      - name: Clone CDDA
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.target-repo }}/Cataclysm-DDA
          fetch-depth: 1
          ref: ios-build

      - name: Install runtime dependencies (mac)
        uses: BrettDong/setup-sdl2-frameworks@v2
        with:
          sdl2: latest
          sdl2-ttf: latest
          sdl2-image: latest
          sdl2-mixer: latest
      - name: Install build dependencies (mac)
        run: |
          HOMEBREW_NO_AUTO_UPDATE=yes HOMEBREW_NO_INSTALL_CLEANUP=yes brew install gettext ccache parallel dylibbundler xcodegen
          pip3 install dmgbuild biplist
      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.3.1
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: fetch sdl2 libs
        run: |
          mkdir -p build/libs/headers
          wget https://github.com/sonphantrung/sdl2ios-compiler/releases/download/SDL2oniOS/sdl2ios.zip
          unzip sdl2ios.zip -d build/libs
          git clone --depth=1 -b release-2.30.8 https://github.com/libsdl-org/SDL
          git clone --depth=1 -b release-2.8.2 https://github.com/libsdl-org/SDL_image
          git clone --depth=1 -b release-2.22.0 https://github.com/libsdl-org/SDL_ttf
          git clone --depth=1 -b release-2.8.0 https://github.com/libsdl-org/SDL_mixer
          cp -f SDL/include/*.h build/libs/headers
          cp -f SDL_image/include/*.h build/libs/headers
          cp -f SDL_mixer/include/*.h build/libs/headers
          cp -f SDL_ttf/SDL_ttf.h build/libs/headers
      - name: xcodegen moment
        run: |
          cd build-scripts
          cp xcode_dev_id_example.yml xcode_dev_id.yml
          xcodegen -s xcodegen-cataclysm.yml -p ../build
      - name: Build IPA
        run: |
          make version
          make prefix
          cd build
          xcrun xcodebuild -project CataclysmExperimental.xcodeproj -scheme CataclysmExperimental -sdk iphoneos \
                                    archive -archivePath ./archive \
                                    CODE_SIGNING_REQUIRED=NO \
                                    AD_HOC_CODE_SIGNING_ALLOWED=YES \
                                    CODE_SIGNING_ALLOWED=NO \
                                    DWARF_DSYM_FOLDER_PATH="."
      - name: actually packing the IPA archive
        run: |
          mkdir Payload
          mkdir Payload/CataclysmExperimental.app
          cp -R build/archive.xcarchive/Products/Applications/CataclysmExperimental.app/ Payload/CataclysmExperimental.app/
          zip -r cddaios.ipa Payload
      - uses: actions/upload-artifact@v4
        with:
          name: cdda
          path: cddaios.ipa
